WIFI_SSID = "XXX"
WIFI_PASS = "XXX"
MQTT_BROKER_IP = "192.168.0.0"
MQTT_BROKER_PORT = 1883
MQTT_CLIENT_ID = "esp1"
MQTT_CLIENT_USER = "XXX"
MQTT_CLIENT_PASSWORD = "XXX"

MQTT_SEND_PERIOD = timerSeconds(10)
MQTT_CONNECT_PERIOD = timerSeconds(5)
MQTT_RELAY_TOPIC = "/ESP/RELAY"
TIMER_WIFI_UPDATE_PERIOD = timerSeconds(10)
PIN_RELAY = 4
BUTTON_CHANGE_STATE_DELAY = 1000000